# Generated by Django 2.0.5 on 2020-02-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200210_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='pic.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
